### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by CrazyPython** [pteichman/cobe#29]
Cobe is really useful. It should be ported to Python 3. I can help with this.

**Comment by pteichman** [comment]
Sounds good to me. I think some people are using 2to3 (at least, I've merged a few commits to help) but if it makes sense to have the master branch target 3 directly, that's fine too.

**Comment by CrazyPython** [comment]
@pteichman At least be compatible. `cobe` is listed as available for Python 3 on PyPI, which it isn't.

**Comment by pteichman** [comment]
Ah! Ok, I'll look into that.

**Comment by chauffer** [comment]
@pteichman any news? I'd love to use this in python3 projects.

**Comment by q2dg** [comment]
Hello?

**Comment by Gustavo6046** [comment]
I still am looking forward to this.

**Comment by koitsu** [comment]
Hello?

**Comment by chauffer** [comment]
Yes hello @koitsu

**Comment by koitsu** [comment]
We're all waiting for some progress on this.  PyStemmer and other pteichman softwares also don't build on newer compilers (ex. clang), so for cobe to work, it seems the effort may be quite large.

**Comment by MrPowerScripts** [comment]
Please add support for python 3! Python 2 is no longer available in Ubuntu 20. The usability of this library is starting to fade and it's still incredibility valuable. Adding python 3 support would reclaim the value for many years if it's possible.

**Comment by corryalpha** [comment]
Add support for python 3. Python 2 is out of date.

**Comment by pteichman** [comment]
Hi folks, I've just uploaded a Python 3 port to PyPI. I'm not using it myself, so feedback is welcome. Thanks for your considerable patience.

Check out https://github.com/pteichman/fate if you're Go inclined. Cobe's main design constraint was minimal memory usage, and because of that it hits disk all the time. Fate keeps its entire model in RAM, and I've got fate models running up to about 760,000 lines of corpus.
